server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / { # Si el archivo existe, lo sirve; si no, devuelve index.html 
    try_files $uri /index.html; 
  }

  # Opcional: servir archivos estáticos con caché 
  location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ { 
    expires 6M; 
    access_log off; 
    add_header Cache-Control "public"; }
}
